### PR TITLE
Fixing SQL connection eating chunkloader recursion bug caused by massive tree farms

### PR DESCRIPTION
**Pull request by caucow**
As title says, see commit descriptions.

### CODE REVIEW

**Comment by ProgrammerDan** [comment]
Pretty cool stuff. Can you toss a version increment into the pom? Just up the minor (last number) by one. 

Level of testing?

**Comment by caucow** [comment]
So far just compile + low effort in-game test to make sure it does what I need and still grows stuff, dunno if I could have broken anything but (pre-patch) just making plants grow when I wanted by messing with the db was frustrating (and I ended up just setting persist time to 0 in the configs to force stuff to grow). Need to make sure I'm building it right (or maybe I'm unintentionally triggering a bug I came across only once some 8ish months ago) and other growth doesn't break, stuff doesn't accidentally double-grow with the chunkload-triggered growth being spaced across multiple ticks, etc.

**Comment by ProgrammerDan** [comment]
Sounds great. I'll merge it -- if you run into any fixes while using, just hit me with another patch.

**Comment by ProgrammerDan** [comment]
Thank you, this is a great contribution!

**Pull request merged**
